using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HraveMzdy.Procezor.Registry.Constants;
using HraveMzdy.Procezor.Registry.Factories;
using HraveMzdy.Procezor.Payrolex.Registry.Constants;
using HraveMzdy.Procezor.Service.Types;

namespace HraveMzdy.Procezor.Payrolex.Registry.Factories
{
    class ServiceArticleFactory : ArticleSpecFactory
    {
        const Int16 ARTICLE_DEFAULT_SEQUENS = 0;

        private readonly IEnumerable<ProviderRecord> ArticleConfig = new ProviderRecord[] {
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_CONTRACT_WORK_TERM, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_CONTRACT_WORK_TERM,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_POSITION_WORK_TERM, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_POSITION_WORK_TERM,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_POSITION_WORK_PLAN, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_POSITION_WORK_PLAN,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_POSITION_TIME_PLAN, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_POSITION_TIME_PLAN,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_POSITION_TIME_WORK, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_POSITION_TIME_WORK,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_POSITION_TIME_ABSC, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_POSITION_TIME_ABSC,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_CONTRACT_TIME_PLAN, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_CONTRACT_TIME_PLAN,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_CONTRACT_TIME_WORK, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_CONTRACT_TIME_WORK,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_CONTRACT_TIME_ABSC, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_CONTRACT_TIME_ABSC,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_PAYMENT_SALARY, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_PAYMENT_BASIS,
                new Int32[] {
                    (Int32)PayrolexArticleConst.ARTICLE_INCOME_GROSS,
                    (Int32)PayrolexArticleConst.ARTICLE_EMPLOYER_COSTS,
                    (Int32)PayrolexArticleConst.ARTICLE_HEALTH_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_SOCIAL_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SUBJECT,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_HEALTH,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SOCIAL,
                }),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_PAYMENT_BONUS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_PAYMENT_FIXED,
                new Int32[] {
                    (Int32)PayrolexArticleConst.ARTICLE_INCOME_GROSS,
                    (Int32)PayrolexArticleConst.ARTICLE_EMPLOYER_COSTS,
                    (Int32)PayrolexArticleConst.ARTICLE_HEALTH_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_SOCIAL_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SUBJECT,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_HEALTH,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SOCIAL,
                }),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_PAYMENT_WORKED, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_PAYMENT_FIXED,
                new Int32[] {
                    (Int32)PayrolexArticleConst.ARTICLE_INCOME_GROSS,
                    (Int32)PayrolexArticleConst.ARTICLE_EMPLOYER_COSTS,
                    (Int32)PayrolexArticleConst.ARTICLE_HEALTH_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_SOCIAL_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SUBJECT,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_HEALTH,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SOCIAL,
                }),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_PAYMENT_BARTER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_PAYMENT_FIXED,
                new Int32[] {
                    (Int32)PayrolexArticleConst.ARTICLE_HEALTH_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_SOCIAL_INCOME,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SUBJECT,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_HEALTH,
                    (Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SOCIAL,
                }),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_ALLOWCE_HOFFICE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_PAYMENT_FIXED,
                new Int32[] {
                    (Int32)PayrolexArticleConst.ARTICLE_INCOME_NETTO,
                }),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_INCOME_GROSS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_INCOME_GROSS,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_INCOME_NETTO, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_INCOME_NETTO,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_EMPLOYER_COSTS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_EMPLOYER_COSTS,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_DECLARE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_DECLARE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_INCOME, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_INCOME,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_BASE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_BASE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_BASE_EMPLOYEE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_BASE_EMPLOYEE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_BASE_EMPLOYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_BASE_EMPLOYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_BASE_MANDATE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_BASE_MANDATE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_BASE_OVERCAP, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_BASE_OVERCAP,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_PAYM_EMPLOYEE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_PAYM_EMPLOYEE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_HEALTH_PAYM_EMPLOYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_HEALTH_PAYM_EMPLOYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_DECLARE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_DECLARE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_INCOME, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_INCOME,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_BASE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_BASE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_BASE_EMPLOYEE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_BASE_EMPLOYEE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_BASE_EMPLOYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_BASE_EMPLOYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_BASE_OVERCAP, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_BASE_OVERCAP,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_PAYM_EMPLOYEE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_PAYM_EMPLOYEE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_SOCIAL_PAYM_EMPLOYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_SOCIAL_PAYM_EMPLOYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_DECLARE, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_DECLARE,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_SIGNING, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_SIGNING,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SUBJECT, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_INCOME_SUBJECT,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_HEALTH, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_INCOME_HEALTH,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_INCOME_SOCIAL, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_INCOME_SOCIAL,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES_INCOME, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES_INCOME,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES_HEALTH, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES_HEALTH,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES_SOCIAL, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES_SOCIAL,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES_BASIS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES_BASIS,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_SOLIDARY_BASIS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_SOLIDARY_BASIS,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_SOLIDARY, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_SOLIDARY,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ADVANCES_TOTAL, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ADVANCES_TOTAL,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_WITHHOLD_INCOME, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_WITHHOLD_INCOME,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_WITHHOLD_HEALTH, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_WITHHOLD_HEALTH,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_WITHHOLD_SOCIAL, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_WITHHOLD_SOCIAL,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_WITHHOLD_BASIS, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_WITHHOLD_BASIS,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_WITHHOLD_TOTAL, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_WITHHOLD_TOTAL,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ALLOWANCE_PAYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ALLOWANCE_PAYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ALLOWANCE_CHILD, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ALLOWANCE_CHILD,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ALLOWANCE_DISAB, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ALLOWANCE_DISAB,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_ALLOWANCE_STUDY, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_ALLOWANCE_STUDY,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_REBATE_PAYER, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_REBATE_PAYER,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_REBATE_CHILD, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_REBATE_CHILD,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_BONUS_CHILD, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_BONUS_CHILD,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_PAYM_ADVANCES, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_PAYM_ADVANCES,
                Array.Empty<Int32>()),
            new ProviderRecord((Int32)PayrolexArticleConst.ARTICLE_TAXING_PAYM_WITHHOLD, ARTICLE_DEFAULT_SEQUENS, (Int32)PayrolexConceptConst.CONCEPT_TAXING_PAYM_WITHHOLD,
                Array.Empty<Int32>()),
       };
        public ServiceArticleFactory()
        {
            this.Providers = BuildProvidersFromRecords(ArticleConfig);
        }
    }
}
