using HraveMzdy.Procezor.Registry.Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HraveMzdy.Procezor.Payrolex.Registry.Constants
{
    public enum PayrolexConceptConst : Int32
    {
        CONCEPT_CONTRACT_WORK_TERM,
        CONCEPT_POSITION_WORK_TERM,
        CONCEPT_POSITION_WORK_PLAN,
        CONCEPT_POSITION_TIME_PLAN,
        CONCEPT_POSITION_TIME_WORK,
        CONCEPT_POSITION_TIME_ABSC,
        CONCEPT_CONTRACT_TIME_PLAN,
        CONCEPT_CONTRACT_TIME_WORK,
        CONCEPT_CONTRACT_TIME_ABSC,
        CONCEPT_PAYMENT_BASIS,
        CONCEPT_PAYMENT_FIXED,
        CONCEPT_HEALTH_DECLARE,
        CONCEPT_HEALTH_INCOME,
        CONCEPT_HEALTH_BASE,
        CONCEPT_HEALTH_BASE_EMPLOYEE,
        CONCEPT_HEALTH_BASE_EMPLOYER,
        CONCEPT_HEALTH_BASE_MANDATE,
        CONCEPT_HEALTH_BASE_OVERCAP,
        CONCEPT_HEALTH_PAYM_EMPLOYEE,
        CONCEPT_HEALTH_PAYM_EMPLOYER,
        CONCEPT_SOCIAL_DECLARE,
        CONCEPT_SOCIAL_INCOME,
        CONCEPT_SOCIAL_BASE,
        CONCEPT_SOCIAL_BASE_EMPLOYEE,
        CONCEPT_SOCIAL_BASE_EMPLOYER,
        CONCEPT_SOCIAL_BASE_OVERCAP,
        CONCEPT_SOCIAL_PAYM_EMPLOYEE,
        CONCEPT_SOCIAL_PAYM_EMPLOYER,
        CONCEPT_TAXING_DECLARE,
        CONCEPT_TAXING_SIGNING,
        CONCEPT_TAXING_INCOME_SUBJECT,
        CONCEPT_TAXING_INCOME_HEALTH,
        CONCEPT_TAXING_INCOME_SOCIAL,
        CONCEPT_TAXING_ADVANCES_INCOME,
        CONCEPT_TAXING_ADVANCES_HEALTH,
        CONCEPT_TAXING_ADVANCES_SOCIAL,
        CONCEPT_TAXING_ADVANCES_BASIS,
        CONCEPT_TAXING_SOLIDARY_BASIS,
        CONCEPT_TAXING_ADVANCES,
        CONCEPT_TAXING_SOLIDARY,
        CONCEPT_TAXING_ADVANCES_TOTAL,
        CONCEPT_TAXING_ALLOWANCE_PAYER,
        CONCEPT_TAXING_ALLOWANCE_CHILD,
        CONCEPT_TAXING_ALLOWANCE_DISAB,
        CONCEPT_TAXING_ALLOWANCE_STUDY,
        CONCEPT_TAXING_REBATE_PAYER,
        CONCEPT_TAXING_REBATE_CHILD,
        CONCEPT_TAXING_BONUS_CHILD,
        CONCEPT_TAXING_WITHHOLD_INCOME,
        CONCEPT_TAXING_WITHHOLD_HEALTH,
        CONCEPT_TAXING_WITHHOLD_SOCIAL,
        CONCEPT_TAXING_WITHHOLD_BASIS,
        CONCEPT_TAXING_WITHHOLD_TOTAL,
        CONCEPT_TAXING_PAYM_ADVANCES,
        CONCEPT_TAXING_PAYM_WITHHOLD,
        CONCEPT_INCOME_GROSS,
        CONCEPT_INCOME_NETTO,
        CONCEPT_EMPLOYER_COSTS,
    }
    public static class ServiceConceptExtensions
    {
        public static string GetSymbol(this PayrolexConceptConst article)
        {
            return article.ToString();
        }
    }
    class ServiceConceptEnumUtils : EnumConstUtils<PayrolexConceptConst>
    {
    }
}
